### ISSUE TITLE
Search option pagination problem based on number of matches

### ISSUE THREAD

**Issue by Vijay4657** [meilisearch/meilisearch-dotnet#133]
We are using the search option with the Offset & Limit properties for the use of pagination using the below code snippet.

var searchQuery = new SearchQuery
                {
                    AttributesToHighlight = new string[] { "title", "description", "updates" },
                    AttributesToCrop = new string[] { "description", "updates" },
                    CropLength = 90,
                    Offset = startIndex,
                    Limit = pageSize,
                    Filters = string.IsNullOrWhiteSpace(filterQuery) ? null : filterQuery,
                };

                var searchResponse = await index.Search<FormattedSearchResult>(keyword, searchQuery).ConfigureAwait(false);
	TotalCount = searchResponse.NbHits;

Based on the change in the Offset & Limit values i.e., startIndex and pageSize the response value for the number of matches property “NbHits”  keeps changing for the same searchQuery parameters as mentioned above. Find the result screenshot we had based on this.

Offset – 0 & Limit – 10.

![image](https://user-images.githubusercontent.com/31198475/122165042-4485cb00-ce95-11eb-9dcb-08934c469d6d.png)

 
Offset – 10 & Limit – 10.

 
![image](https://user-images.githubusercontent.com/31198475/122165056-494a7f00-ce95-11eb-8d32-ec0bb50f4678.png)

As it can be seen above from the screenshots values of the NbHits property varies while increasing the Offset value for the same query & search parameters. This makes the pagination improper for the same search keyword and search parameters. We are using Meilisearch version 0.20.0. And meilisearch dotnet version is 0.4.2

Is this an existing bug.? Or Any work around available for this issue.?

**Comment by curquiza** [comment]
Hello,

`nbHits` is not relevant to be used as `TotalCount`.
Please check the following issues in MeiliSearch:
- https://github.com/meilisearch/MeiliSearch/issues/911
- https://github.com/meilisearch/MeiliSearch/issues/1120

And here is a guide to help you implement the pagination you wish: https://github.com/meilisearch/documentation/issues/561

Also, FYI, we are currently thinking of improving the API so that it makes the pagination easier.

We are sorry for this confusion. 

I close this issue since it has nothing to do with this repository (the dotnet SDK) but MeiliSearch itself.
