### ISSUE TITLE
Downgrade to 4.6.2 deps

### ISSUE THREAD

**Issue by mrmaxonline** [meilisearch/meilisearch-dotnet#169]
Please do it.

**Comment by curquiza** [comment]
hello!
Can you be a little bit more explicit please? :)

**Comment by mrmaxonline** [comment]
U have nuget package only STD2.0 but our project compatible with 4.6.2 .net - with standard2.0 we have a problem bacause it's not own core of project. Can u expand a nuget package for 4.5, 4.6.2 and other targets ?

**Comment by curquiza** [comment]
I'm not sure to really understand what you need, could you please open a PR, and then, we will let you know if you can merge it or not? :)

**Comment by sander1095** [comment]
@curquiza Perhaps I can be of help.

This library targets [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) which is a collection of API's that are guaranteed to work on multiple .NET flavors, like `mono`, `.NET framework`, `.NET Core`, etc..

There are multiple versions of .NET standard like 1.0, 1.1, 1.2, etc...., 2.0.
Each version introduces new API's, but older versions of those flavors of .NET will not implement newer versions since they are EOL.

.NET Standard 2.0 is the most popular version because of it's huge amount of API's, but not all flavors implement this.
You can find a compatibility chart in my first link. 

The idea of .NET Standard of library creators is to target the lowest version of .NET Standard possible so your library can be used by biggest amount of framework versions possible. If you target .NET Standard 2.0 even though you use none of the API's introduced in 2.0, there is no reason to target 2.0 and you are better off targeting 1.8 or something instead so projects with older framework versions can still use your library!

@mrmaxonline is asking to downgrade the .NET standard version to a version with a lower amount of API's available (if possible) so the library can run on .NET Framework 4.5 and 4.6.2. 

Now the funny thing, the compatibility chart says that 4.6.2 should support .NET standard 2.0 with some caveats. @mrmaxonline  also requests .NET Framework 4.5 support, which would mean that we'd have to decrease the .NET Standard version.

Another funny thing is that microsoft does recommend to [not target lower than 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target), so I would have serious doubts about doing this.

.NET framework is already kind of "legacy"... but 4.5 and 4.6.x especially so. If @mrmaxonline  would upgrade their project to .NET Framework 4.7 or 4.8 they could use this library in an official manner. As an outsider I would advice this approach!

**Comment by mrmaxonline** [comment]
![image](https://user-images.githubusercontent.com/12570364/137435506-8563aabe-dae5-49a1-b9a4-4bd2f044de8c.png)
Libraries STD2.0 crashes the system

**Comment by sander1095** [comment]
@mrmaxonline  that screenshot doesn't tell me much. It's just some random software? And the screenshot just says everything is OK.. 

Does this software use meilisearch? Are you perhaps writing this issue in the wrong repo?

Can you show us where it crashes? What is the exact error? Etc..

**Comment by curquiza** [comment]
Hello @sander1095  and @mrmaxonline 

Thank you so much @sander1095 for this clear and detailed explanation! 🔥 

<img width="912" alt="Capture d’écran 2021-10-18 à 20 52 20" src="https://user-images.githubusercontent.com/20380692/137789767-1aaad02f-8699-4d0c-bf6a-a141a6ca51c4.png">

Since Microsoft recommends using .NET Standard 2.0, I would rather keep doing this and not starting a complex maintenance.

> .NET framework is already kind of "legacy"... but 4.5 and 4.6.x especially so. If @mrmaxonline would upgrade their project to .NET Framework 4.7 or 4.8 they could use this library in an official manner. As an outsider I would advice this approach!

I agree with you @sander1095 

I close this issue then since we will not change this at the moment.

Feel free to ask me to re-open if I miss understand something.
