### ISSUE TITLE
Issue with null values between AddDocumentsAsync & UpdateDocumentsAsync

### ISSUE THREAD

**Issue by juchom** [meilisearch/meilisearch-dotnet#231]
**Description**
With actual code, we have an issue with null values in two different parts of the code.

To understand this issue we will do a simple exemple with the following object.

```csharp
public class Person
{
	public string Name { get; set; }
	public int? Age { get; set; }
}
```

Let's see how things are working now :

```csharp
void Main()
{
	var p = new Person { Name = "John", Age = 12 };
	JsonSerializer.Serialize((new List<Person> { p }).RemoveNullValues()).Dump(); // OUTPUT : [{"name":"John","age":12}]
	p.Age = null;
	JsonSerializer.Serialize((new List<Person> { p }).RemoveNullValues()).Dump(); // OUTPUT : [{"name":"John"}]
}
```

The first problem here is the method `RemoveNullValues`, this method is only called in `UpdateDocumentsAsync` and not in `AddDocumentsAsync`.
The second problem is, if we index the whole Person object, the Age field could never be set back to `null`.

I would strongly suggest to delete the `RemoveNullValues`, this method is useless and you will see it next.

Next problem is the default `JsonSerializerOption`

```csharp
public static readonly JsonSerializerOptions JsonSerializerOptions = new JsonSerializerOptions
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
};
```

If we modify a little bit the program above like this to use the default `JsonSerializerOptions` like this :
```csharp
void Main()
{
	var p = new Person { Name = "John", Age = 12 };
	JsonSerializer.Serialize((new List<Person> { p }), JsonSerializerOptions).Dump(); // OUTPUT : [{"name":"John","age":12}]
	p.Age = null;
	JsonSerializer.Serialize((new List<Person> { p }), JsonSerializerOptions).Dump(); // OUTPUT : [{"name":"John"}]
}
```

We solved a part of the problem, we don't have to use a custom method to  remove the `null` values, the JsonSerializer is taking care of it.

But we still have the issue if we want to set to `null` the Age field in our index.

What I would suggest is to update the default `JsonSerializerOptions` to

```csharp
public static readonly JsonSerializerOptions JsonSerializerOptions = new JsonSerializerOptions
{
    DefaultIgnoreCondition = JsonIgnoreCondition.Never,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
};
```

And if we run out program again 

If we modify a little bit the program above like to use the default `JsonSerializerOptions` like this :
```csharp
void Main()
{
	var p = new Person { Name = "John", Age = 12 };
	JsonSerializer.Serialize((new List<Person> { p }), JsonSerializerOptions).Dump(); // OUTPUT : [{"name":"John","age":12}]
	p.Age = null;
	JsonSerializer.Serialize((new List<Person> { p }), JsonSerializerOptions).Dump(); // OUTPUT : [{"name":"John","age":null}]
}
```

We are now sending the `null` to the index and we should have the same behavior between `AddDocumentsAsync` and `UpdateDocumentsAsync`

If you're ok with that I will do the PR

**Comment by brunoocasali** [comment]
Hello @juchom thanks for letting us know about this problem, I wasn’t aware of that :/

Just a question, do you think this behavior is affecting other methods than that these two you commented on? Your proposed solution could work for them (or impact somehow)?

@curquiza do you think this `null` behavior is intentional from the core side?

**Comment by juchom** [comment]
I saw that when I was working on the support of ndjson and csv.

The PR was too big, I'll make some PR / issues to fix what I've found.

Sorry @brunoocasali, I didn't answer all of your questions :
Concerning the `RemoveNullValues` method, this one is used only in `UpdateDocumentsAsync`. This method has to be removed from the codebase.

Concerning the behavior of this change in the JsonSerializerOptions, you have to check 11 references of it.

**Comment by brunoocasali** [comment]
Yes let's remove: `RemoveNullValues` from the `UpdateDocumentsAsync` to make it even with the `AddDocumentsAsync` 🥇 

Now about the `JsonSerializerOptions`, I checked the implementations and some of them require the current behavior (we should not send the attribute when the attribute is `null`) [this guide](https://docs.meilisearch.com/reference/api/settings.html#update-settings) mentions that we should leave untouched the keys that we don't want to change, otherwise they will be reset unintentionally _for the settings call_.

So, in summary I tried to map all the usages and possible changes:

- `SearchAsync` (uses `MeilisearchClient.JsonSerializerOptions` options should keep the current behavior)
- `UpdateSettingsAsync` (uses `MeilisearchClient.JsonSerializerOptions` options should keep the current behavior)
- `CreateIndexAsync` (uses `MeilisearchClient.JsonSerializerOptions` options should keep the current behavior)
- `CreateKeyAsync` (uses `JsonNamingPolicy.CamelCase` only and define it directly in the method)
- `AddDocumentsAsync` (uses `JsonNamingPolicy.CamelCase` only)
- All the child settings updates like `UpdateStopWordsAsync`, `UpdateSynonymsAsync` could use the `JsonIgnoreCondition.Never` (but to evict problems we could avoid changing them). 

We could create global json options, to be shared when it needed - like the client one, but for all the cases - what do you think?

I was looking these implementations for so long that I probably forgot something, but is definitely a starting point!

**Comment by juchom** [comment]
I'm on your side with this, let start with this and we will do the fixing if needed. I'll let you finish the work on the analytics and the chunk issue and I'll open a PR. This will avoid potential merge conflicts.
