### ISSUE TITLE
 .net core api authorization 

### ISSUE THREAD

**Issue by romanymg** [meilisearch/meilisearch-dotnet#491]
**Description**
just use meilisearch package
my .net core api authorization 
aways return 401

**Expected behavior**
What you expected to happen.

**Current behavior**
What happened.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: [e.g. v.0.20.0]
- meilisearch-dotnet version: [e.g v0.6.0]

**Comment by curquiza** [comment]
Hey @romanymg 

Looks like your issue is more related to a support need and not a request for feature or a bug fix. 401 means you have not provided the right key to access the route.

I would recommend going to our [Discord](https://discord.gg/meilisearch) instead. The community will be able to help you, no matter your question.

Thanks for using Meilisearch!
