### ISSUE TITLE
Implement dumps

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-dotnet#69]
Since [v0.15.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0), MeiliSearch exposes a new functionality: [dumps](https://docs.meilisearch.com/references/dump.html#dumps)

This feature should be implemented in this SDK following [this specificacions](https://github.com/meilisearch/integration-guides/issues/44)

- [ ] Implement dump creation route
- [ ] Implement get dump status route
- [ ] Add tests
<s>- [ ] Add code samples</s> not available for this SDK

**Comment by AlexNDRmac** [comment]
@eskombro I can help you with it.

**Comment by curquiza** [comment]
Hello @AlexNDRmac!
This issue is still available! Feel free to start it and to ask any questions if needed 🙂

**Comment by eskombro** [comment]
Amazing @AlexNDRmac , thanks a lot!

**Comment by AlexNDRmac** [comment]
@curquiza could you please add `hacktoberfest-accepted` label to my PR #76 because in my profile this PR looks like not valid.

**Comment by curquiza** [comment]
Hello @AlexNDRmac!
I don't need to add this label because the "hacktoberfest" topic is present in this repo.

<img width="1649" alt="Capture d’écran 2020-11-04 à 09 47 55" src="https://user-images.githubusercontent.com/20380692/98089501-19f57d80-1e83-11eb-9cf7-215555ec53ba.png">

See the [Hacktoberfest rules](https://hacktoberfest.digitalocean.com/#rules).

And even in the FAQ:

<img width="1550" alt="Capture d’écran 2020-11-04 à 09 52 17" src="https://user-images.githubusercontent.com/20380692/98089746-79ec2400-1e83-11eb-97e3-1d4699855492.png">

None of our contributors had any problems... Maybe it's because the official approval was done after the 31st of October. So sorry for that, I have a lot of repos to maintain and I did not realize you were doing that for the Hacktoberfest event...

**Comment by AlexNDRmac** [comment]
Ok, thanks :)
